### ISSUE TITLE
Probblem converting VCF to Joinmap format

### ISSUE THREAD

**Issue by avdanurag** [NGSEP/NGSEPcore#3]
Hi, I am trying to convert VCF file (generated using taasel 5) in to join map format but output only contains header. Please look in to this issue.  Here is my command

java -jar NGSEPcore_3.3.0.jar ConvertVCF -printJoinMap -p1 PB1.CEL_call_code -p2 SS.CEL_call_code trail_rice.vcf trail_rice_geno

**Comment by jduitama** [comment]
Hi @avdanurag 

My apologies for the delayed answer. I thought it was the same issue reported in sourceforge. Would you mind sharing the first few variants in your VCF to try to reproduce the issue?. Make sure that you have homozygous differences between your parental lines. You can run the filter command selecting only the two parents and the option -fi and see if you still get variants.

Best regards

Jorge
