### ISSUE TITLE
Empty Vcf file

### ISSUE THREAD

**Issue by hafizmtalha** [NGSEP/NGSEPcore#30]
Hi,
I am using this tool for GBS analysis. I did alignment using ReadAligner and now I m trying to get multi sample variants file. But every time my vcf file comes empty. why is it so ??any help ??
I tried singlesample comand as well that's empty too..

**Comment by jduitama** [comment]
Hi

My apologies for the delayed answer. I have better track of our discussion in sourceforge. In any case, can you please share with me the log file of the process?. This is the best source to track potential erros.
