### ISSUE TITLE
'0/1' genotypes a vcf generated with SingleSampleVariantsDetector a -ploidy 1 option

### ISSUE THREAD

**Issue by Acanthodasha** [NGSEP/NGSEPcore#33]
I'm sorry, could you suggest, why after genotype calling of a haploid organism 
with SingleSampleVariantsDetector with -ploidy 1 option the resultant .vcf contains '0/1' genotypes, please?
I've used the following command:
ngsep SingleSampleVariantsDetector -runRep -runRD -runRP -minQuality 30 -ploidy 1 -sampleId {some sample Id} -r {reference} -i {input} -o {some sample}_Q30
Such genotypes are also present in Demo_ann_q40_s_fi_I2_noREP_noCNV.vcf.
I've done calling on the same bam file with another caller, and it tends to render the genotypes at the same positions as '1' in the vcf, but I want to use ngsep.
I've done genotype calling from the same bam file using another caller, and it tends to render genotypes at the corresponding positions as '1', but I want to use ngsep.

**Comment by jduitama** [comment]
This issue was solved at our FAQ at sourceforge: https://sourceforge.net/p/ngsep/discussion/faq
