### ISSUE TITLE
Exception in thread "pool-1-thread-1" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by pjx1990** [NGSEP/NGSEPcore#41]
When I use NGSEPcore to align the reads to the reference genome, I get a lot of errors:
Exception in thread "pool-1-thread-****" java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer.

My command is:
java -jar /home/biosoft/NGSEPcore_4.1.0/NGSEPcore.jar ReadsAligner -i fq/test1.fastq.gz -o test1.bam -r /my/genome.fa -d /my/genome.fa.index -s test1

I don't know where I went wrong, hope your reply.

**Comment by jduitama** [comment]
Thanks for your interest in NGSEP. This is a common error that we found trying to run NGSEP with java 1.8. In part for that reason, we decided to move to java 11 or superior. Please double check which version of java are you running. You can do this running the command 

java -version

If you do not wish to install a new version of java, you can just download and decompress the jdk 11 (or superior) in any path, and then use the full path to the java executable (usually in the bin subfolder).

let me know how things go.

**Comment by pjx1990** [comment]
Thank your reply. The java version as follows:
openjdk version "1.8.0_92"
OpenJDK Runtime Environment (Zulu 8.15.0.1-linux64) (build 1.8.0_92-b15)
OpenJDK 64-Bit Server VM (Zulu 8.15.0.1-linux64) (build 25.92-b15, mixed mode)

I tried NGSEP version3 and it works fine。

**Comment by jduitama** [comment]
Great. TO run the new version, you need to download the jdk 11 or superior. If you do not have superuser rights, you can just download and uncompress the jdk and write the full path to the java program within the jdk distribution
