### ISSUE TITLE
Making NGSEP 4.2.1

### ISSUE THREAD

**Issue by Rem1burwell** [NGSEP/NGSEPcore#42]
<img width="1015" alt="Screen Shot 2022-06-27 at 2 33 09 PM" src="https://user-images.githubusercontent.com/95144030/176011594-3d39e592-4ee1-41d3-bb0c-1fbfd25fd2c7.png">

I am having issues making NGSEP 4.2.1 and have tried the instructions in the README file.  When following those directions, the file cannot be found in the directory and is not .tar.gz as listed in the instructions.  I am operating on a cluster and used git to grab the whole NGSEPcore, so I am confused as to why it can not find the file in the directory.  I have included a screenshot of what happens when I try to use the make file.  Thanks :)

**Comment by Rem1burwell** [comment]
Thanks! I checked the version by using `java -version` and found the cluster only uses Java 8. So now I need to find a workaround to use the newer version- the tutorial says at least version 11 is required.

**Comment by jduitama** [comment]
Hi
Thanks for the question and the answer. I just released officially version 4.2.1. About java, if you do not have admin rights, you can just download and decompress the distribution of java 11 most appropriate for your operative system and use the full path to the java executable to run NGSEP, as well as other java programs
