### ISSUE TITLE
How to use TransposableElementsFinder and TransposableElementAnnotation

### ISSUE THREAD

**Issue by xiekunwhy** [NGSEP/NGSEPcore#43]
Hi,

I found [TransposableElementAnnotation.java](https://github.com/NGSEP/NGSEPcore/blob/master/src/ngsep/genome/TransposableElementAnnotation.java) and [TransposableElementsFinder.java](https://github.com/NGSEP/NGSEPcore/blob/master/src/ngsep/genome/TransposableElementsFinder.java), how to use then now?

Best,
Kun

**Comment by jduitama** [comment]
Dear Kun

Thanks for your interest in NGSEP. By now the TransposableElementsFinder is not available in the official releases because this is still an early development. We plan to have a version with competitive results in the next couple of months.

Best regards

Jorge
