### ISSUE TITLE
How to get a vcf output from SV calling pipeline?

### ISSUE THREAD

**Issue by kcleal** [NGSEP/NGSEPcore#46]
Hi,
Thanks for the nice tool chain. Ive run the SV calling pipeline but no vcf file is produced, only a gff file. How do I obtain a vcf file? My command was:
```
java -jar NGSEPcore_4.3.1.jar SingleSampleVariantsDetector -runOnlySVs -i sample.cram -r ref.fasta -o samp -runLongReadSVs -sampleId samp
```

**Comment by ngaitan55** [comment]
Hi Kez, 
I appreciate your interest. I see you closed the thread but still, it is worth noting that version 4.3.2 now provides a vcf including only SVs with the parameters you used. Please let us know if you have further questions about the functionality.
