### ISSUE TITLE
Low coverage samples

### ISSUE THREAD

**Issue by kcleal** [NGSEP/NGSEPcore#47]
Hi,
Im trying to run NGSEP on a single PacBio Sequel II flow cell, e.g. SRR10382244 from SRA (coverage 7.6x). Data is aligned using minimap2 and Im calling SVs using:

    java -jar NGSEPcore_4.3.2.jar SingleSampleVariantsDetector -runOnlySVs -runLongReadSVs -i SRR103822${i}.mm2.bam -r hs37d5.fa -o HG002_${i}.pacbio.NGSEP.vcf

However I seem to be getting quite low precision and recall, compared to what was expected. Are there any options to use to help call low coverage samples?

**Comment by kcleal** [comment]
Actually, I just figured out what was happening, I forgot to use the `-p 0` option when using Truvari.

**Comment by ngaitan55** [comment]
Hi Kez

I have made a quick experiment with this sample and the results are reasonably as expected, using Truvari for comparison with the gold standard provided by the GIAB consortium. Precisely, these are the command and the performance metrics using the Tier 1 region:

`truvari bench -b HG002_SVs_Tier1_v0.6.vcf.gz -c "$file.gz" -f $ref -r 1000 -p 0.00 -o $dir_prefix --passonly --includebed HG002_SVs_Tier1_v0.6.bed`

> {
>     "TP-base": 8432,
>     "TP-call": 8432,
>     "FP": 609,
>     "FN": 1209,
>     "precision": 0.9326401946687314,
>     "recall": 0.8745980707395499,
>     "f1": 0.9026870784712558,
>     "base cnt": 9641,
>     "call cnt": 9041,
>     "TP-call_TP-gt": 7725,
>     "TP-call_FP-gt": 707,
>     "TP-base_TP-gt": 7725,
>     "TP-base_FP-gt": 707,
>     "gt_concordance": 0.9161527514231499,
>     "gt_matrix": {
>         "(1, 1)": {
>             "(1, 1)": 3954,
>             "(0, 1)": 169
>         },
>         "(0, 1)": {
>             "(1, 1)": 538,
>             "(0, 1)": 3771
>         }
>     
> 
> }


Please tell me how you estimated the precision and recall values and the software you used for this, so I can further help you improve your results with NGSEP. Thank you.
